import type { Metadata } from 'next'
import { Lato } from "next/font/google";
import './globals.css'
import ToastContainerProvider from "./components/ToastContainerProvider";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main className="h-screen overflow-y-auto">
          <ToastContainerProvider>{children}</ToastContainerProvider>
        </main>
      </body>
    </html>
  )
}
